// Generated by CoffeeScript 1.6.1
(function() {
  var consts, pkg, w;

  pkg = this.pkg || {};

  consts = this.consts;

  w = this;

  pkg.utils.BodyFactory = (function() {

    BodyFactory.prototype._kc = pkg.utils.KrackConverter;

    BodyFactory.world = null;

    function BodyFactory() {
      /*
      			Util method to create a body body
      				@method createbox
      				@public
      				@param {int} the x position of the body in pixels
      				@param {int} the y position of the body in pixels
      				@param {int} the width of the body
      				@param {int} the height of the body
      				@param {boolean:false} if the body is dynamic or not
      				@param {string} data to attach to the body for use later
      */
      this.createBox = function(px, py, w, h, d, isSen, ud) {
        var bodyDef, fixDef, shape;
        if (d == null) {
          d = false;
        }
        if (isSen == null) {
          isSen = false;
        }
        if (ud == null) {
          ud = "";
        }
        bodyDef = new w.b2BodyDef();
        shape = new w.b2PolygonShape();
        fixDef = new w.b2FictureDef();
        bodyDef.position.Set(this._kc.getMeters(px), this._kc.getMeters(py));
        if (d) {
          bodyDef.type = w.b2Body.b2_dynamicBody;
        }
        shape.SetAsBox(this._kc.getMeters(w), this._kc.getMeters(h));
        fixDef.isSensor = isSen;
        fixDef.shape = shape;
        fixDef.userData = ud;
        return body;
      };
    }

    return BodyFactory;

  })();

}).call(this);
