// Generated by CoffeeScript 1.6.1
(function() {
  var consts, pkg, w;

  pkg = this.pkg || {};

  consts = this.consts;

  w = this;

  pkg.utils.KrackConverter = (function() {

    function KrackConverter() {}

    KrackConverter._RATIO = 30;

    KrackConverter.getPixels = function(meters) {
      return meters * pkg.utils.KrackConverter._RATIO;
    };

    KrackConverter.getMeters = function(pixels) {
      return pixels / pkg.utils.KrackConverter._RATIO;
    };

    return KrackConverter;

  })();

}).call(this);
