// Generated by CoffeeScript 1.6.1
(function() {
  var consts, pkg, w;

  pkg = this.pkg || {};

  consts = this.consts;

  w = this;

  pkg.utils.KrackConverter = (function() {
    var _RATIO;

    function KrackConverter() {}

    _RATIO = 30;

    KrackConverter.getPixels = function(meters) {
      return meters * this._RATIO;
    };

    KrackConverter.getMeters = function(pixels) {
      return pixels / this._RATIO;
    };

    return KrackConverter;

  })();

}).call(this);
