// Generated by CoffeeScript 1.6.1
(function() {
  var window, _ref;

  window = (_ref = typeof GLOBAL === "undefined") != null ? _ref : {
    window: GLOBAL
  };

  this.consts = {
    worldWidth: 2000
  };

}).call(this);
