// Generated by CoffeeScript 1.6.1
(function() {
  var window;

  window = typeof exports !== "undefined" && exports !== null ? exports : this;

  window.namespace = {
    com: {
      krakencoder: {
        utils: {}
      }
    }
  };

  window.pkg = window.namespace.com.krakencoder;

  window.consts = {
    worldWidth: 2000,
    worldHeight: 1000,
    windowMidWidth: typeof $ !== "undefined" ? $(window).width() / 2 : false,
    windowMidHeight: typeof $ !== "undefined" ? $(window).height() / 2 : false,
    offsetX: 0,
    offsetY: 0,
    fps: 1000 / 60,
    timestep: 1 / 60,
    velocity_iter: 10,
    position_iter: 10,
    gravity: 9.8,
    debug: true,
    playerCategory: 0x001,
    playerMask: 0x000,
    playerGroupIndex: -1,
    stage: null,
    foregroundContainer: null,
    playerContainer: null,
    backgroundContainer: null,
    middleBackgroundContainer: null,
    farBackgroundContainer: null,
    mouseX: 0,
    mouseY: 0,
    speed_limit: 9,
    player_force: 1.5,
    $canvasContainer: null,
    canvas: null,
    debugCanvas: null,
    context: null,
    debugContext: null,
    port: 9000,
    io: null,
    auth: null,
    onAuth: "iConnected",
    newClient: "biggerPartyStart",
    onDisconnect: "peaceOut!",
    playerMove: "playerMove",
    updatePlayer: "updatePlayer"
  };

  window.b2Vec2 = Box2D.Common.Math.b2Vec2;

  window.b2AABB = Box2D.Collision.b2AABB;

  window.b2BodyDef = Box2D.Dynamics.b2BodyDef;

  window.b2Body = Box2D.Dynamics.b2Body;

  window.b2FixtureDef = Box2D.Dynamics.b2FixtureDef;

  window.b2Fixture = Box2D.Dynamics.b2Fixture;

  window.b2World = Box2D.Dynamics.b2World;

  window.b2MassData = Box2D.Collision.Shapes.b2MassData;

  window.b2PolygonShape = Box2D.Collision.Shapes.b2PolygonShape;

  window.b2CircleShape = Box2D.Collision.Shapes.b2CircleShape;

  window.b2DebugDraw = Box2D.Dynamics.b2DebugDraw;

  window.b2MouseJointDef = Box2D.Dynamics.Joints.b2MouseJointDef;

  window.listener = new Box2D.Dynamics.b2ContactListener;

  window.contactEdge = Box2D.Dynamics.Contacts.b2ContactEdge;

}).call(this);
