// Generated by CoffeeScript 1.6.1
(function() {
  var Kraken, com;

  com = {
    krakencoder: {}
  };

  com.krakencoder.Kraken = (function() {

    function Kraken() {}

    Kraken.prototype.init = function() {
      console.log("init");
      return false;
    };

    return Kraken;

  })();

  Kraken = new com.krakencoder.Kraken;

  window.onload = Kraken.init;

}).call(this);
