// Generated by CoffeeScript 1.6.1
(function() {
  var consts, pkg, win;

  pkg = this.pkg || {};

  consts = this.consts;

  win = this;

  pkg.KrakenWorld = (function() {
    var bodyFactory;

    KrakenWorld.prototype._debug = null;

    KrakenWorld.prototype._callback = null;

    KrakenWorld.prototype.world = null;

    KrakenWorld.prototype.kill = [];

    bodyFactory = null;

    function KrakenWorld(debug, updateCallback) {
      this._debug = debug != null ? debug : false;
      this._callback = updateCallback != null ? updateCallback : false;
      this._startBox2D();
    }

    KrakenWorld.prototype._startBox2D = function() {
      return this._setupWorld();
    };

    KrakenWorld.prototype._setupWorld = function() {
      this.world = new win.b2World(new win.b2Vec2(0, consts.gravity), true);
      return console.log("setup world");
    };

    return KrakenWorld;

  })();

}).call(this);
