// Generated by CoffeeScript 1.6.1
(function() {
  var consts, pkg, w;

  pkg = this.pkg || {};

  consts = this.consts;

  w = this;

  pkg.ui.Keyboard = (function() {

    function Keyboard() {}

    Keyboard.west = false;

    Keyboard.east = false;

    Keyboard.north = false;

    Keyboard.south = false;

    Keyboard._upAllowed = true;

    Keyboard._inited = false;

    Keyboard.init = function() {
      if (!Keyboard._inited) {
        Keyboard._inited = true;
        $(window).on("keydown", Keyboard._onKeyDown);
        $(window).on("keyup", Keyboard._onKeyDown);
        return $(window).on("resetup", Keyboard._resetUp);
      }
    };

    Keyboard._onKeyDown = function(e) {
      switch (e.keyCode) {
        case 37:
        case 65:
          return Keyboard.west = e.type === "keydown";
        case 38:
        case 87:
          if (e.type === "keydown" && Keyboard._upAllowed) {
            Keyboard.north = true;
            return Keyboard._upAllowed = false;
          }
          break;
        case 39:
        case 68:
          return Keyboard.east = e.type === "keydown";
      }
    };

    Keyboard._resetUp = function(e) {
      Keyboard.north = false;
      return Keyboard._upAllowed = true;
    };

    return Keyboard;

  })();

}).call(this);
